# Generated by Django 4.1 on 2022-08-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Name', models.CharField(max_length=20)),
                ('Monthly_Price', models.IntegerField()),
                ('Yearly_Price', models.IntegerField()),
                ('Video_Quality', models.CharField(max_length=10)),
                ('Resolution', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('4K', '4K'), ('4K+HDR', '4K+HDR')], default='480p', max_length=10)),
                ('Devices', models.CharField(max_length=25)),
                ('Active_Screens', models.IntegerField()),
            ],
        ),
    ]
